language: python
python: 
    - "3.8"

install:
    - pip install pipenv
    - pipenv install

script:
    - ./manage.py makemigrations
    - ./manage.py migrate
    - ./manage.py migrate --run-syncdb
    - pipenv run tests
    