language: python
python:
  - '3.8'

install:
  - pip install pipenv
  - pipenv install

script:
  - "./manage.py makemigrations"
  - "./manage.py migrate"
  - "./manage.py migrate --run-syncdb"

test_script:
  - pipenv run tests

deploy:
  provider: heroku
  api_key:
    secure: KM5eFG/c1iwkiYkRYK3mhXRGojJcRcJqT3DJ2oBXjbVZG34/4w2PSQY6jNT8H2PD0Yg6OjdRoPFvuWGMTOCsjKxGNtKX+DXmy+QHw6MqMbQ4MryQOt6ZTp+ekbN7ukcRb0Z3dsslK4xCHtqPz0Ozf9YMnhZlllLtM7grti8dwrI+bWBQn6I4/V9svYeDm6FWSJJZYHMc5+6kfRKvDQ+7pAv6GEu/SgVa8tCAejcBEU1o0oPU1em0eM9SXUHEvJAJIjS2JS0eC4YvXcAqCoW0btqVsvWyvYm8l9M8xdss/m+/dhUSoVlk3T5VdbQgAsI+7rAxXcain1qM9Celas2jeBx8MXS4SA7LZiuD1rbqjhF+QH1vIAYYRBV5KT1v6axSOk/TfdES/A693TrUF/xuvdsCrD1JZKXLkoQfGe6FiK4DX8w2J2mvDjCqSp3lPyobmk94KwXaTuGaOegWzeeYFvOeTKpOZoLdXlvnmL3YX1U99eP1xbbjElSqL/wU3VOzZwzU2/y/EoKKSWwWJnOx91F+QpnGnRNQQPcK0nAJJEtlTqIIvNeKO4bUdIacd99SaFwgAWspiKo4CYrM+EDR5RZOXlXa//GRs5rxLtV1oHnpfOJnkjcim8KU4mshyP5Y5vsWoea+uoLfUahCzkkwwPfA14yn454l4tYxs4VkNuk=
  app: jjpaulo2
  edge: true
  run:
    - python ./manage.py makemigrations
    - python ./manage.py migrate
    - python ./manage.py migrate --run-syncdb
