# Generated by Django 3.1 on 2021-01-07 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210106_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='habilidade',
            name='descricao',
            field=models.TextField(default=None),
        ),
    ]
