# Generated by Django 3.1 on 2021-01-20 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_habilidade_descricao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educacao',
            options={'verbose_name': 'educação', 'verbose_name_plural': 'formações'},
        ),
        migrations.AlterModelOptions(
            name='experiencia',
            options={'verbose_name': 'experiência profissional', 'verbose_name_plural': 'experiências'},
        ),
        migrations.AlterModelOptions(
            name='habilidade',
            options={'verbose_name': 'habilidade/tecnologia', 'verbose_name_plural': 'habilidades'},
        ),
        migrations.AlterModelOptions(
            name='paragrafodescricao',
            options={'verbose_name': 'paragrafo de descrição', 'verbose_name_plural': 'paragrafos de descrição'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'trabalho', 'verbose_name_plural': 'portfólio'},
        ),
        migrations.AlterModelOptions(
            name='projetoeducacao',
            options={'verbose_name': 'projeto realizado durante formação', 'verbose_name_plural': 'projetos'},
        ),
        migrations.AlterModelOptions(
            name='redesocial',
            options={'verbose_name': 'rede social', 'verbose_name_plural': 'Redes sociais'},
        ),
        migrations.AlterModelOptions(
            name='sobre',
            options={'verbose_name': 'informação', 'verbose_name_plural': 'sobre mim'},
        ),
        migrations.AddField(
            model_name='sobre',
            name='foto',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='perfil'),
        ),
        migrations.AlterField(
            model_name='projetoeducacao',
            name='instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='api.educacao'),
        ),
    ]
