# Generated by Django 3.1 on 2021-01-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210120_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='sobre',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
    ]
